/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class network_loki_sessionrouter_SessionRouterVPN */

#ifndef _Included_network_loki_sessionrouter_SessionRouterVPN
#define _Included_network_loki_sessionrouter_SessionRouterVPN
#ifdef __cplusplus
extern "C"
{
#endif
    /*
     * Class:     network_loki_sessionrouter_SessionRouterVPN
     * Method:    PacketSize
     * Signature: ()I
     */
    JNIEXPORT jint JNICALL Java_network_loki_sessionrouter_SessionRouterVPN_PacketSize(JNIEnv*, jclass);

    /*
     * Class:     network_loki_sessionrouter_SessionRouterVPN
     * Method:    Alloc
     * Signature: ()Ljava/nio/Buffer;
     */
    JNIEXPORT jobject JNICALL Java_network_loki_sessionrouter_SessionRouterVPN_Alloc(JNIEnv*, jclass);

    /*
     * Class:     network_loki_sessionrouter_SessionRouterVPN
     * Method:    Free
     * Signature: (Ljava/nio/Buffer;)V
     */
    JNIEXPORT void JNICALL Java_network_loki_sessionrouter_SessionRouterVPN_Free(JNIEnv*, jclass, jobject);

    /*
     * Class:     network_loki_sessionrouter_SessionRouterVPN
     * Method:    Stop
     * Signature: ()V
     */
    JNIEXPORT void JNICALL Java_network_loki_sessionrouter_SessionRouterVPN_Stop(JNIEnv*, jobject);

    /*
     * Class:     network_loki_sessionrouter_SessionRouterVPN
     * Method:    ReadPkt
     * Signature: (Ljava/nio/ByteBuffer;)I
     */
    JNIEXPORT jint JNICALL Java_network_loki_sessionrouter_SessionRouterVPN_ReadPkt(JNIEnv*, jobject, jobject);

    /*
     * Class:     network_loki_sessionrouter_SessionRouterVPN
     * Method:    WritePkt
     * Signature: (Ljava/nio/ByteBuffer;)Z
     */
    JNIEXPORT jboolean JNICALL Java_network_loki_sessionrouter_SessionRouterVPN_WritePkt(JNIEnv*, jobject, jobject);

    /*
     * Class:     network_loki_sessionrouter_SessionRouterVPN
     * Method:    SetInfo
     * Signature: (Lnetwork/loki/sessionrouter/SessionRouterVPN/VPNInfo;)V
     */
    JNIEXPORT void JNICALL Java_network_loki_sessionrouter_SessionRouterVPN_SetInfo(JNIEnv*, jobject, jobject);
#ifdef __cplusplus
}
#endif
#endif
