/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class network_loki_sessionrouter_SessionRouterVPN_VPNInfo */

#ifndef _Included_network_loki_sessionrouter_SessionRouterVPN_VPNInfo
#define _Included_network_loki_sessionrouter_SessionRouterVPN_VPNInfo
#ifdef __cplusplus
extern "C"
{
#endif
#ifdef __cplusplus
}
#endif
#endif
