/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class network_loki_sessionrouter_SessionRouterDaemon */

#ifndef _Included_network_loki_sessionrouter_SessionRouterDaemon
#define _Included_network_loki_sessionrouter_SessionRouterDaemon
#ifdef __cplusplus
extern "C"
{
#endif
    /*
     * Class:     network_loki_sessionrouter_SessionRouterDaemon
     * Method:    Obtain
     * Signature: ()Ljava/nio/ByteBuffer;
     */
    JNIEXPORT jobject JNICALL Java_network_loki_sessionrouter_SessionRouterDaemon_Obtain(JNIEnv*, jclass);

    /*
     * Class:     network_loki_sessionrouter_SessionRouterDaemon
     * Method:    Free
     * Signature: (Ljava/nio/ByteBuffer;)V
     */
    JNIEXPORT void JNICALL Java_network_loki_sessionrouter_SessionRouterDaemon_Free(JNIEnv*, jclass, jobject);

    /*
     * Class:     network_loki_sessionrouter_SessionRouterDaemon
     * Method:    Configure
     * Signature: (Lnetwork/loki/sessionrouter/SessionRouterConfig;)Z
     */
    JNIEXPORT jboolean JNICALL Java_network_loki_sessionrouter_SessionRouterDaemon_Configure(JNIEnv*, jobject, jobject);

    /*
     * Class:     network_loki_sessionrouter_SessionRouterDaemon
     * Method:    Mainloop
     * Signature: ()I
     */
    JNIEXPORT jint JNICALL Java_network_loki_sessionrouter_SessionRouterDaemon_Mainloop(JNIEnv*, jobject);

    /*
     * Class:     network_loki_sessionrouter_SessionRouterDaemon
     * Method:    IsRunning
     * Signature: ()Z
     */
    JNIEXPORT jboolean JNICALL Java_network_loki_sessionrouter_SessionRouterDaemon_IsRunning(JNIEnv*, jobject);

    /*
     * Class:     network_loki_sessionrouter_SessionRouterDaemon
     * Method:    Stop
     * Signature: ()Z
     */
    JNIEXPORT jboolean JNICALL Java_network_loki_sessionrouter_SessionRouterDaemon_Stop(JNIEnv*, jobject);

    /*
     * Class:     network_loki_sessionrouter_SessionRouterDaemon
     * Method:    InjectVPNFD
     * Signature: ()V
     */
    JNIEXPORT void JNICALL Java_network_loki_sessionrouter_SessionRouterDaemon_InjectVPNFD(JNIEnv*, jobject);

    /*
     * Class:     network_loki_sessionrouter_SessionRouterDaemon
     * Method:    GetUDPSocket
     * Signature: ()I
     */
    JNIEXPORT jint JNICALL Java_network_loki_sessionrouter_SessionRouterDaemon_GetUDPSocket(JNIEnv*, jobject);

    /*
     * Class:     network_loki_sessionrouter_SessionRouterDaemon
     * Method:    DetectFreeRange
     * Signature: ()Ljava/lang/String;
     */
    JNIEXPORT jstring JNICALL Java_network_loki_sessionrouter_SessionRouterDaemon_DetectFreeRange(JNIEnv*, jclass);

    /*
     * Class:     network_loki_sessionrouter_SessionRouterDaemon
     * Method:    DumpStatus
     * Signature: ()Ljava/lang/String;
     */
    JNIEXPORT jstring JNICALL Java_network_loki_sessionrouter_SessionRouterDaemon_DumpStatus(JNIEnv*, jobject);

#ifdef __cplusplus
}
#endif
#endif
